import { BeckhoffSymbol } from './src/services/PlcStructure';

const test: BeckhoffSymbol[] = [
  {
    name: 'Energie.dummy',
    type: 'WORD',
    iGroup: 16448,
    iOffset: 1182,
    bitSize: 16,
  },
  {
    name: '.Anfang',
    type: 'INT',
    comment: 'AA = Anfangszeichen einer Datenaufzeichnung',
    iGroup: 16448,
    iOffset: 0,
    bitSize: 16,
  },
  {
    name: '.Ende',
    type: 'INT',
    comment: 'EE = Endezeichen einer Datenaufzeichnung',
    iGroup: 16448,
    iOffset: 2,
    bitSize: 16,
  },
  {
    name: '.maxDateien',
    type: 'INT',
    comment: 'Wieviel Dateien dürfen maximal im TOC angelegt werden',
    iGroup: 16448,
    iOffset: 4,
    bitSize: 16,
  },
  {
    name: '.maxEnergieSpeicherPlatz',
    type: 'REAL',
    comment: 'maximaler Speicherplatz der für die Eengieaufzeichnung verwendet werden darf in kByte',
    iGroup: 16448,
    iOffset: 8,
    bitSize: 32,
  },
  {
    name: '.maxOwSpeicherPlatz',
    type: 'REAL',
    comment: 'maximaler Speicherplatz der für die Eengieaufzeichnung verwendet werden darf in kByte',
    iGroup: 16448,
    iOffset: 12,
    bitSize: 32,
  },
  {
    name: '.maxTelegrammSpeicherPlatz',
    type: 'REAL',
    comment: 'maximaler Speicherplatz der für die Eengieaufzeichnung verwendet werden darf in kByte',
    iGroup: 16448,
    iOffset: 16,
    bitSize: 32,
  },
  {
    name: '.EnergiePufferMax',
    type: 'DINT',
    comment: 'maximale größe des Energiepuffers',
    iGroup: 16448,
    iOffset: 20,
    bitSize: 32,
  },
  {
    name: '.EnergiemessungTriggerMin',
    type: 'DINT',
    comment: 'minimale Triggerzeit für die Energiemessung in Sekunden',
    iGroup: 16448,
    iOffset: 24,
    bitSize: 32,
  },
  {
    name: '.EnergiemessungTriggerMax',
    type: 'DINT',
    comment: 'maximale Triggerzeit füt die Energiemessung in Sekunden',
    iGroup: 16448,
    iOffset: 28,
    bitSize: 32,
  },
  {
    name: '.AMSPORT_LOGGER',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 420,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_EVENTLOG',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 422,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_RTIME',
    type: 'UINT',
    comment: 'R0 Real time',
    iGroup: 16448,
    iOffset: 424,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_IO',
    type: 'UINT',
    comment: 'I/O Driver',
    iGroup: 16448,
    iOffset: 426,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_NC',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 428,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_NCSAF',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 430,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_NCSVB',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 432,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_ISG',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 434,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_CNC',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 436,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_LINE',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 438,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_PLC',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 440,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_PLC_RTS1',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 442,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_PLC_RTS2',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 444,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_PLC_RTS3',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 446,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_PLC_RTS4',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 448,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_CAM',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 450,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R0_CAMTOOL',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 452,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R3_SYSSERV',
    type: 'UINT',
    comment: 'System Service',
    iGroup: 16448,
    iOffset: 454,
    bitSize: 16,
  },
  {
    name: '.AMSPORT_R3_SCOPESERVER',
    type: 'UINT',
    comment: 'Ads states',
    iGroup: 16448,
    iOffset: 456,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_INVALID',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 458,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_IDLE',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 460,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_RESET',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 462,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_INIT',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 464,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_START',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 466,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_RUN',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 468,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_STOP',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 470,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_SAVECFG',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 472,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_LOADCFG',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 474,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_POWERFAILURE',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 476,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_POWERGOOD',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 478,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_ERROR',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 480,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_SHUTDOWN',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 482,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_SUSPEND',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 484,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_RESUME',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 486,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_CONFIG',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 488,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_RECONFIG',
    type: 'UINT',
    iGroup: 16448,
    iOffset: 490,
    bitSize: 16,
  },
  {
    name: '.ADSSTATE_MAXSTATES',
    type: 'UINT',
    comment: 'max. number of available ads states',
    iGroup: 16448,
    iOffset: 492,
    bitSize: 16,
  },
  {
    name: '.ADSIGRP_SYMTAB',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 496,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYMNAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 500,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYMVAL',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 504,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_HNDBYNAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 508,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_VALBYNAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 512,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_VALBYHND',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 516,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_RELEASEHND',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 520,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_INFOBYNAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 524,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_VERSION',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 528,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_INFOBYNAMEEX',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 532,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_DOWNLOAD',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 536,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_UPLOAD',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 540,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYM_UPLOADINFO',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 544,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_SYMNOTE',
    type: 'UDINT',
    comment: 'notification OF named handle',
    iGroup: 16448,
    iOffset: 548,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_RWIB',
    type: 'UDINT',
    comment: 'read/write input BYTE(S)',
    iGroup: 16448,
    iOffset: 552,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_RWIX',
    type: 'UDINT',
    comment: 'read/write input bit',
    iGroup: 16448,
    iOffset: 556,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_RISIZE',
    type: 'UDINT',
    comment: 'read input size (in BYTE)',
    iGroup: 16448,
    iOffset: 560,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_RWOB',
    type: 'UDINT',
    comment: 'read/write output BYTE(S)',
    iGroup: 16448,
    iOffset: 564,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_RWOX',
    type: 'UDINT',
    comment: 'read/write output bit',
    iGroup: 16448,
    iOffset: 568,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_ROSIZE',
    type: 'UDINT',
    comment: 'read/write output bit',
    iGroup: 16448,
    iOffset: 572,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_CLEARI',
    type: 'UDINT',
    comment: 'write inputs TO null',
    iGroup: 16448,
    iOffset: 576,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_CLEARO',
    type: 'UDINT',
    comment: 'write outputs TO null',
    iGroup: 16448,
    iOffset: 580,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_IOIMAGE_RWIOB',
    type: 'UDINT',
    comment: 'read input AND write output BYTE(S) ADS-READWRITE',
    iGroup: 16448,
    iOffset: 584,
    bitSize: 32,
  },
  {
    name: '.ADSIGRP_DEVICE_DATA',
    type: 'UDINT',
    comment: 'state, name, etc...',
    iGroup: 16448,
    iOffset: 588,
    bitSize: 32,
  },
  {
    name: '.ADSIOFFS_DEVDATA_ADSSTATE',
    type: 'UDINT',
    comment: 'ads state OF device',
    iGroup: 16448,
    iOffset: 592,
    bitSize: 32,
  },
  {
    name: '.ADSIOFFS_DEVDATA_DEVSTATE',
    type: 'UDINT',
    comment: 'device state',
    iGroup: 16448,
    iOffset: 596,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_OPENCREATE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 600,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_OPENREAD',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 604,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_OPENWRITE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 608,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_CREATEFILE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 612,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_CLOSEHANDLE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 616,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FOPEN',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 620,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FCLOSE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 624,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FREAD',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 628,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FWRITE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 632,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FSEEK',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 636,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FTELL',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 640,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FGETS',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 644,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FPUTS',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 648,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FSCANF',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 652,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FPRINTF',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 656,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FEOF',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 660,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FDELETE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 664,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_FRENAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 668,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_MKDIR',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 672,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_RMDIR',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 676,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_REG_HKEYLOCALMACHINE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 680,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_SENDEMAIL',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 684,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_TIMESERVICES',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 688,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_STARTPROCESS',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 692,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_CHANGENETID',
    type: 'UDINT',
    comment: 'System service index offsets: SYSTEMSERVICE_TIMESERVICES',
    iGroup: 16448,
    iOffset: 696,
    bitSize: 32,
  },
  {
    name: '.TIMESERVICE_DATEANDTIME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 700,
    bitSize: 32,
  },
  {
    name: '.TIMESERVICE_SYSTEMTIMES',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 704,
    bitSize: 32,
  },
  {
    name: '.TIMESERVICE_RTCTIMEDIFF',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 708,
    bitSize: 32,
  },
  {
    name: '.TIMESERVICE_ADJUSTTIMETORTC',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 712,
    bitSize: 32,
  },
  {
    name: '.TIMESERVICE_TIMEZONINFORMATION',
    type: 'UDINT',
    comment: 'ADSLOGxxx log control mask types',
    iGroup: 16448,
    iOffset: 716,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_HINT',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 720,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_WARN',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 724,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_ERROR',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 728,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_LOG',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 732,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_MSGBOX',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 736,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_RESOURCE',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 740,
    bitSize: 32,
  },
  {
    name: '.ADSLOG_MSGTYPE_STRING',
    type: 'DWORD',
    comment: 'boot data constants (-> SYSTEMINFOTYPE.bootDataFlags)',
    iGroup: 16448,
    iOffset: 744,
    bitSize: 32,
  },
  {
    name: '.BOOTDATAFLAGS_RETAIN_LOADED',
    type: 'BYTE',
    iGroup: 16448,
    iOffset: 494,
    bitSize: 8,
  },
  {
    name: '.BOOTDATAFLAGS_RETAIN_INVALID',
    type: 'BYTE',
    iGroup: 16448,
    iOffset: 495,
    bitSize: 8,
  },
  {
    name: '.BOOTDATAFLAGS_RETAIN_REQUESTED',
    type: 'BYTE',
    iGroup: 16448,
    iOffset: 748,
    bitSize: 8,
  },
  {
    name: '.BOOTDATAFLAGS_PERSISTENT_LOADED',
    type: 'BYTE',
    iGroup: 16448,
    iOffset: 749,
    bitSize: 8,
  },
  {
    name: '.BOOTDATAFLAGS_PERSISTENT_INVALID',
    type: 'BYTE',
    comment: 'system state constants (-> SYSTEMINFOTYPE.systemStateFlags)',
    iGroup: 16448,
    iOffset: 750,
    bitSize: 8,
  },
  {
    name: '.SYSTEMSTATEFLAGS_BSOD',
    type: 'BYTE',
    comment: 'blue screen of death',
    iGroup: 16448,
    iOffset: 751,
    bitSize: 8,
  },
  {
    name: '.SYSTEMSTATEFLAGS_RTVIOLATION',
    type: 'BYTE',
    comment: 'realtime violation - latency time',
    iGroup: 16448,
    iOffset: 752,
    bitSize: 8,
  },
  {
    name: '.FOPEN_MODEREAD',
    type: 'DWORD',
    comment: '"r": Opens for reading. If the file does not exist or cannot be found, the call fails.',
    iGroup: 16448,
    iOffset: 756,
    bitSize: 32,
  },
  {
    name: '.FOPEN_MODEWRITE',
    type: 'DWORD',
    comment: '"w": Opens an empty file for writing. If the given file exists, its contents are destroyed.',
    iGroup: 16448,
    iOffset: 760,
    bitSize: 32,
  },
  {
    name: '.FOPEN_MODEAPPEND',
    type: 'DWORD',
    comment:
      '"a": Opens for writing at the end of the file (appending) without removing the EOF marker before writing new data to the file; creates the file first if it doesn’t exist.',
    iGroup: 16448,
    iOffset: 764,
    bitSize: 32,
  },
  {
    name: '.FOPEN_MODEPLUS',
    type: 'DWORD',
    comment: '"+": Opens for reading and writing',
    iGroup: 16448,
    iOffset: 768,
    bitSize: 32,
  },
  {
    name: '.FOPEN_MODEBINARY',
    type: 'DWORD',
    comment: '"b": Open in binary (untranslated) mode.',
    iGroup: 16448,
    iOffset: 772,
    bitSize: 32,
  },
  {
    name: '.FOPEN_MODETEXT',
    type: 'DWORD',
    comment: '"t": Open in text (translated) mode.',
    iGroup: 16448,
    iOffset: 776,
    bitSize: 32,
  },
  {
    name: '.FILE_OPENCREATE',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 780,
    bitSize: 32,
  },
  {
    name: '.FILE_OPENREAD',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 784,
    bitSize: 32,
  },
  {
    name: '.FILE_OPENWRITE',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 788,
    bitSize: 32,
  },
  {
    name: '.FILE_READ',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 792,
    bitSize: 32,
  },
  {
    name: '.FILE_WRITE',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 796,
    bitSize: 32,
  },
  {
    name: '.FILE_SEEKBEGIN',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 800,
    bitSize: 32,
  },
  {
    name: '.FILE_SEEKEND',
    type: 'DWORD',
    comment: 'END OF OBSOLETE FILE OPERATION CONSTANTS',
    iGroup: 16448,
    iOffset: 804,
    bitSize: 32,
  },
  {
    name: '.TCEVENTFLAG_PRIOCLASS',
    type: 'WORD',
    comment: 'event class/priority\tthrough textformatter',
    iGroup: 16448,
    iOffset: 754,
    bitSize: 16,
  },
  {
    name: '.TCEVENTFLAG_FMTSELF',
    type: 'WORD',
    comment: 'format in message',
    iGroup: 16448,
    iOffset: 808,
    bitSize: 16,
  },
  {
    name: '.TCEVENTFLAG_LOG',
    type: 'WORD',
    comment: 'write to log file',
    iGroup: 16448,
    iOffset: 810,
    bitSize: 16,
  },
  {
    name: '.TCEVENTFLAG_MSGBOX',
    type: 'WORD',
    comment: 'display message box',
    iGroup: 16448,
    iOffset: 812,
    bitSize: 16,
  },
  {
    name: '.TCEVENTFLAG_SRCID',
    type: 'WORD',
    comment: 'src id instead of source name',
    iGroup: 16448,
    iOffset: 814,
    bitSize: 16,
  },
  {
    name: '.TCEVENTFLAG_AUTOFMTALL',
    type: 'WORD',
    comment: 'event states',
    iGroup: 16448,
    iOffset: 816,
    bitSize: 16,
  },
  {
    name: '.TCEVENTSTATE_INVALID',
    type: 'WORD',
    comment: 'event object is not initialized',
    iGroup: 16448,
    iOffset: 818,
    bitSize: 16,
  },
  {
    name: '.TCEVENTSTATE_SIGNALED',
    type: 'WORD',
    comment: 'event object is in a signaled state',
    iGroup: 16448,
    iOffset: 820,
    bitSize: 16,
  },
  {
    name: '.TCEVENTSTATE_RESET',
    type: 'WORD',
    comment: 'event object is in a reset state',
    iGroup: 16448,
    iOffset: 822,
    bitSize: 16,
  },
  {
    name: '.TCEVENTSTATE_CONFIRMED',
    type: 'WORD',
    comment: 'event object is confirmed but not reset',
    iGroup: 16448,
    iOffset: 824,
    bitSize: 16,
  },
  {
    name: '.TCEVENTSTATE_RESETCON',
    type: 'WORD',
    comment: 'event object is confirmed and reset',
    iGroup: 16448,
    iOffset: 826,
    bitSize: 16,
  },
  {
    name: '.TCEVENT_SRCNAMESIZE',
    type: 'INT',
    iGroup: 16448,
    iOffset: 828,
    bitSize: 16,
  },
  {
    name: '.TCEVENT_FMTPRGSIZE',
    type: 'INT',
    iGroup: 16448,
    iOffset: 830,
    bitSize: 16,
  },
  {
    name: '.PI',
    type: 'LREAL',
    iGroup: 16448,
    iOffset: 832,
    bitSize: 64,
  },
  {
    name: '.DEFAULT_ADS_TIMEOUT',
    type: 'TIME',
    iGroup: 16448,
    iOffset: 840,
    bitSize: 32,
  },
  {
    name: '.MAX_STRING_LENGTH',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 844,
    bitSize: 32,
  },
  {
    name: '.MAX_ADAPTER_NAME_LENGTH',
    type: 'UDINT',
    comment: '256 + 4 inkl. \\0',
    iGroup: 16448,
    iOffset: 912,
    bitSize: 32,
  },
  {
    name: '.MAX_ADAPTER_DESCRIPTION_LENGTH',
    type: 'UDINT',
    comment: '128 + 4 inkl. \\0',
    iGroup: 16448,
    iOffset: 916,
    bitSize: 32,
  },
  {
    name: '.MAX_ADAPTER_ADDRESS_LENGTH',
    type: 'UDINT',
    comment: 'Physical adapter address bytes[0..7]',
    iGroup: 16448,
    iOffset: 920,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_IPHELPERAPI',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 924,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_IPHOSTNAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 928,
    bitSize: 32,
  },
  {
    name: '.IPHELPERAPI_ADAPTERSINFO',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 932,
    bitSize: 32,
  },
  {
    name: '.IPHELPERAPI_IPADDRBYHOSTNAME',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 936,
    bitSize: 32,
  },
  {
    name: '.MAX_LOCAL_ADAPTERS',
    type: 'UDINT',
    comment: 'Max. number of local adapters',
    iGroup: 16448,
    iOffset: 940,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_ADDREMOTE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 944,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_DELREMOTE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 948,
    bitSize: 32,
  },
  {
    name: '.SYSTEMSERVICE_ENUMREMOTE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 952,
    bitSize: 32,
  },
  {
    name: '.MAX_REMOTE_PCS',
    type: 'INT',
    iGroup: 16448,
    iOffset: 956,
    bitSize: 16,
  },
  {
    name: '.ROUTE_FLAG_TEMPORARY',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 960,
    bitSize: 32,
  },
  {
    name: '.ROUTE_FLAG_DYNAMIC',
    type: 'DWORD',
    comment: 'hostname instead OF IP address',
    iGroup: 16448,
    iOffset: 964,
    bitSize: 32,
  },
  {
    name: '.ROUTE_FLAG_NOOVERRIDE',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 968,
    bitSize: 32,
  },
  {
    name: '.MAX_ROUTE_NAME_LEN',
    type: 'BYTE',
    comment: 'max. TcRouter length',
    iGroup: 16448,
    iOffset: 753,
    bitSize: 8,
  },
  {
    name: '.MAX_ROUTE_ADDR_LEN',
    type: 'BYTE',
    comment: 'max. TcRouter length',
    iGroup: 16448,
    iOffset: 958,
    bitSize: 8,
  },
  {
    name: '.MIN_ROUTE_TRANSPORT',
    type: 'BYTE',
    comment: 'eRouteTransport_None',
    iGroup: 16448,
    iOffset: 959,
    bitSize: 8,
  },
  {
    name: '.MAX_ROUTE_TRANSPORT',
    type: 'BYTE',
    comment: 'eRouteTransport_SOAP',
    iGroup: 16448,
    iOffset: 972,
    bitSize: 8,
  },
  {
    name: '.SYSTEMSERVICE_FFILEFIND',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 976,
    bitSize: 32,
  },
  {
    name: '.HKEY_MAX_BINARY_DATA_SIZE',
    type: 'UDINT',
    comment: 'Ams logger constants',
    iGroup: 16448,
    iOffset: 980,
    bitSize: 32,
  },
  {
    name: '.AMSLOGGER_IGR_GENERAL',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 984,
    bitSize: 32,
  },
  {
    name: '.AMSLOGGER_IOF_MODE',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 988,
    bitSize: 32,
  },
  {
    name: '.AMSPORT_AMSLOGGER',
    type: 'UINT',
    comment: 'Format string constants',
    iGroup: 16448,
    iOffset: 974,
    bitSize: 16,
  },
  {
    name: '.FORMAT_MAX_ARGS',
    type: 'INT',
    comment: 'max number of format arguments in FB_FormatString',
    iGroup: 16448,
    iOffset: 992,
    bitSize: 16,
  },
  {
    name: '.FLOATREC_EXP_IS_NAN',
    type: 'INT',
    comment: 'the value is #NAN or -#NAN',
    iGroup: 16448,
    iOffset: 994,
    bitSize: 16,
  },
  {
    name: '.FLOATREC_EXP_IS_INF',
    type: 'INT',
    comment: 'the value is #INF or -#INF',
    iGroup: 16448,
    iOffset: 996,
    bitSize: 16,
  },
  {
    name: '.FLOATREC_MAX_DIGITS',
    type: 'INT',
    comment: 'Note: double precision floats have max. 15 significant digits',
    iGroup: 16448,
    iOffset: 998,
    bitSize: 16,
  },
  {
    name: '.FLOATREC_MAX_PRECISION',
    type: 'INT',
    comment: 1e-307,
    iGroup: 16448,
    iOffset: 1000,
    bitSize: 16,
  },
  {
    name: '.FLOATREC_MIN_PRECISION',
    type: 'INT',
    comment: 'FB_FormatString function block error codes: Error code == argument number (1..10) + error code',
    iGroup: 16448,
    iOffset: 1002,
    bitSize: 16,
  },
  {
    name: '.FMTERR_NOERROR',
    type: 'DWORD',
    comment: 'No error',
    iGroup: 16448,
    iOffset: 1004,
    bitSize: 32,
  },
  {
    name: '.FMTERR_PERCENTSIGNPOSITION',
    type: 'DWORD',
    comment: 'Percent sign (%) at invalid position',
    iGroup: 16448,
    iOffset: 1008,
    bitSize: 32,
  },
  {
    name: '.FMTERR_ASTERISKPOSITION',
    type: 'DWORD',
    comment: 'Asterisk parameter at invalid position',
    iGroup: 16448,
    iOffset: 1012,
    bitSize: 32,
  },
  {
    name: '.FMTERR_WIDTHVALUE',
    type: 'DWORD',
    comment: 'Invalid width field value',
    iGroup: 16448,
    iOffset: 1016,
    bitSize: 32,
  },
  {
    name: '.FMTERR_PRECISIONVALUE',
    type: 'DWORD',
    comment: 'invalid precision field value',
    iGroup: 16448,
    iOffset: 1020,
    bitSize: 32,
  },
  {
    name: '.FMTERR_FLAGPOSITION',
    type: 'DWORD',
    comment: 'one of the flags at invalid position',
    iGroup: 16448,
    iOffset: 1024,
    bitSize: 32,
  },
  {
    name: '.FMTERR_WIDTHPRECISIONVALPOS',
    type: 'DWORD',
    comment: 'the width or precision field value at invalid position',
    iGroup: 16448,
    iOffset: 1028,
    bitSize: 32,
  },
  {
    name: '.FMTERR_PRECISIONDOTPOSITION',
    type: 'DWORD',
    comment: 'dot "." sign of precision field at invalid position',
    iGroup: 16448,
    iOffset: 1032,
    bitSize: 32,
  },
  {
    name: '.FMTERR_TYPEFIELDVALUE',
    type: 'DWORD',
    comment: 'invalid (unsupported) type field value',
    iGroup: 16448,
    iOffset: 1036,
    bitSize: 32,
  },
  {
    name: '.FMTERR_ARGTYPEINVALID',
    type: 'DWORD',
    comment: 'Different type field and argument parameter',
    iGroup: 16448,
    iOffset: 1040,
    bitSize: 32,
  },
  {
    name: '.FMTERR_UNACCEPTEDPARAMETER',
    type: 'DWORD',
    comment: 'Invalid format string parameters',
    iGroup: 16448,
    iOffset: 1044,
    bitSize: 32,
  },
  {
    name: '.FMTERR_INSUFFICIENTARGS',
    type: 'DWORD',
    comment: 'To much arguments in format string',
    iGroup: 16448,
    iOffset: 1048,
    bitSize: 32,
  },
  {
    name: '.FMTERR_DESTBUFFOVERFLOW',
    type: 'DWORD',
    comment: 'Destination string buffer overflow (formatted string is to long )',
    iGroup: 16448,
    iOffset: 1052,
    bitSize: 32,
  },
  {
    name: '.SYSTEMTIME_DATEDELTA_OFFSET',
    type: 'DWORD',
    comment: 'number of past days since year zero until 1 January 1601',
    iGroup: 16448,
    iOffset: 1056,
    bitSize: 32,
  },
  {
    name: '.MIN_SBCS_TABLE',
    type: 'INT',
    iGroup: 16448,
    iOffset: 1060,
    bitSize: 16,
  },
  {
    name: '.MAX_SBCS_TABLE',
    type: 'INT',
    iGroup: 16448,
    iOffset: 1062,
    bitSize: 16,
  },
  {
    name: '.DATE_AND_TIME_SECPERDAY',
    type: 'DWORD',
    comment: 'Number of seconds per day',
    iGroup: 16448,
    iOffset: 1064,
    bitSize: 32,
  },
  {
    name: '.DATE_AND_TIME_SECPERWEEK',
    type: 'DWORD',
    comment: 'Number of seconds per week',
    iGroup: 16448,
    iOffset: 1068,
    bitSize: 32,
  },
  {
    name: '.MAX_BASIC_HASHTABLE_CHAINSIZE',
    type: 'DWORD',
    comment: 'Hash table chain size',
    iGroup: 16448,
    iOffset: 1072,
    bitSize: 32,
  },
  {
    name: '.DBG_OUTPUT_NONE',
    type: 'DWORD',
    comment: 'Disabled (no debug oputput)',
    iGroup: 16448,
    iOffset: 1084,
    bitSize: 32,
  },
  {
    name: '.DBG_OUTPUT_LOG',
    type: 'DWORD',
    comment: 'Enabled, TwinCAT System Manager Log',
    iGroup: 16448,
    iOffset: 1088,
    bitSize: 32,
  },
  {
    name: '.DBG_OUTPUT_FILE',
    type: 'DWORD',
    comment: 'Enabled, text file',
    iGroup: 16448,
    iOffset: 1092,
    bitSize: 32,
  },
  {
    name: '.DBG_OUTPUT_VISU',
    type: 'DWORD',
    comment: 'reserved',
    iGroup: 16448,
    iOffset: 1096,
    bitSize: 32,
  },
  {
    name: '.DEFAULT_CSV_FIELD_DOUBLE_QUOTE',
    type: 'BYTE',
    comment: 'double-quote (") => used to enclose special characters like line breaks, double-quotes, commas...',
    iGroup: 16448,
    iOffset: 973,
    bitSize: 8,
  },
  {
    name: '.DEFAULT_CSV_RECORD_SEP_CR',
    type: 'BYTE',
    comment: 'cariage return => record separator (first character)',
    iGroup: 16448,
    iOffset: 1078,
    bitSize: 8,
  },
  {
    name: '.DEFAULT_CSV_RECORD_SEP_LF',
    type: 'BYTE',
    comment: 'line feed => record separator (second character)',
    iGroup: 16448,
    iOffset: 1079,
    bitSize: 8,
  },
  {
    name: '.Stromausfall',
    type: 'FB_S_UPS_CX80xx',
    comment: 'FB um die itnerne USV zu überwachen',
    iGroup: 16448,
    iOffset: 1224,
    bitSize: 3520,
  },
  {
    name: '.Abschalten',
    type: 'TOF',
    iGroup: 16448,
    iOffset: 1664,
    bitSize: 192,
  },
  {
    name: '.fbSystemZeit',
    type: 'NT_GetTime',
    comment: 'Systemzeit des Windowssystems holen',
    iGroup: 16448,
    iOffset: 932804,
    bitSize: 1632,
  },
  {
    name: '.SystemInfo',
    type: 'FW_SystemInfoType',
    iGroup: 16416,
    iOffset: 32768,
    bitSize: 336,
  },
  {
    name: '.SystemTaskInfoArr',
    type: 'ARRAY [1..4] OF FW_SystemTaskInfoType',
    iGroup: 16416,
    iOffset: 32832,
    bitSize: 1152,
  },
  {
    name: '.EnergieDateistep',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 1736,
    bitSize: 32,
  },
  {
    name: '.EnergieWrite',
    type: 'BOOL',
    comment: 'steigende Flanke um den schreibprozess zu initialisieren',
    iGroup: 16448,
    iOffset: 1726,
    bitSize: 8,
  },
  {
    name: '.EnergieNetId',
    type: 'STRING(23)',
    comment: 'TwinCAT system Netzwerkadresse',
    iGroup: 16448,
    iOffset: 1740,
    bitSize: 192,
  },
  {
    name: '.EnergieFileName',
    type: 'STRING(255)',
    comment: 'Dateiname',
    iGroup: 16448,
    iOffset: 1764,
    bitSize: 2048,
  },
  {
    name: '.EnergieFileHandler',
    type: 'UINT',
    comment: 'File Handler',
    iGroup: 16448,
    iOffset: 2020,
    bitSize: 16,
  },
  {
    name: '.EnergieBusy',
    type: 'BOOL',
    iGroup: 16448,
    iOffset: 1727,
    bitSize: 8,
  },
  {
    name: '.EnergieError',
    type: 'BOOL',
    iGroup: 16448,
    iOffset: 2022,
    bitSize: 8,
  },
  {
    name: '.EnergieErrId',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 2024,
    bitSize: 32,
  },
  {
    name: '.EnergieDateiGroesse',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 2028,
    bitSize: 32,
  },
  {
    name: '.EnergiePufferTemp',
    type: 'ARRAY [0..1024] OF BYTE',
    comment: 'Puffer: eine Binäre Zeile',
    iGroup: 16448,
    iOffset: 2032,
    bitSize: 8200,
  },
  {
    name: '.EnergiePufferTempLaenge',
    type: 'UDINT',
    comment: 'Länge des Puffers',
    iGroup: 16448,
    iOffset: 3060,
    bitSize: 32,
  },
  {
    name: '.fbEnergieFileOpen',
    type: 'FB_FileOpen',
    comment: 'Öffnet Dateien',
    iGroup: 16448,
    iOffset: 3064,
    bitSize: 3360,
  },
  {
    name: '.fbEnergieFileClose',
    type: 'FB_FileClose',
    comment: 'Schließt Dateien',
    iGroup: 16448,
    iOffset: 3484,
    bitSize: 1120,
  },
  {
    name: '.fbEnergieFileWrite',
    type: 'FB_FileWrite',
    comment: 'Daten in Datei schreiben',
    iGroup: 16448,
    iOffset: 3624,
    bitSize: 1312,
  },
  {
    name: '.fbEnergieDatenpuffer',
    type: 'FB_MemBufferMerge',
    comment: 'Datenpuffer zusammen setzten',
    iGroup: 16448,
    iOffset: 3788,
    bitSize: 288,
  },
  {
    name: '.fbEnergieGroesse',
    type: 'FB_FileTell',
    comment: 'Größe der Datei ermitteln',
    iGroup: 16448,
    iOffset: 3824,
    bitSize: 1152,
  },
  {
    name: '.fbEnergieLoeschen',
    type: 'FB_FileDelete',
    comment: 'Datei löschen',
    iGroup: 16448,
    iOffset: 3968,
    bitSize: 3200,
  },
  {
    name: '.OwDateistep',
    type: 'DWORD',
    iGroup: 16448,
    iOffset: 32,
    bitSize: 32,
  },
  {
    name: '.OwWrite',
    type: 'BOOL',
    comment: 'steigende Flanke um den schreibprozess zu initialisieren',
    iGroup: 16448,
    iOffset: 6,
    bitSize: 8,
  },
  {
    name: '.OwNetId',
    type: 'STRING(23)',
    comment: 'TwinCAT system Netzwerkadresse',
    iGroup: 16448,
    iOffset: 1688,
    bitSize: 192,
  },
  {
    name: '.OwFileName',
    type: 'STRING(255)',
    comment: 'Dateiname',
    iGroup: 16448,
    iOffset: 4368,
    bitSize: 2048,
  },
  {
    name: '.OwFileHandler',
    type: 'UINT',
    comment: 'File Handler',
    iGroup: 16448,
    iOffset: 1222,
    bitSize: 16,
  },
  {
    name: '.OwBusy',
    type: 'BOOL',
    iGroup: 16448,
    iOffset: 7,
    bitSize: 8,
  },
  {
    name: '.OwError',
    type: 'BOOL',
    iGroup: 16448,
    iOffset: 1221,
    bitSize: 8,
  },
  {
    name: '.OwErrId',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 1712,
    bitSize: 32,
  },
  {
    name: '.OwDateiGroesse',
    type: 'UDINT',
    iGroup: 16448,
    iOffset: 1716,
    bitSize: 32,
  },
  {
    name: '.OwPufferTemp',
    type: 'ARRAY [0..1024] OF BYTE',
    comment: 'Puffer: eine Binäre Zeile',
    iGroup: 16448,
    iOffset: 4624,
    bitSize: 8200,
  },
  {
    name: '.OwPufferTempLaenge',
    type: 'UDINT',
    comment: 'Länge des Puffers',
    iGroup: 16448,
    iOffset: 1720,
    bitSize: 32,
  },
  {
    name: '.fbOwFileOpen',
    type: 'FB_FileOpen',
    comment: 'Öffnet Dateien',
    iGroup: 16448,
    iOffset: 5692,
    bitSize: 3360,
  },
  {
    name: '.fbOwFileClose',
    type: 'FB_FileClose',
    comment: 'Schließt Dateien',
    iGroup: 16448,
    iOffset: 6112,
    bitSize: 1120,
  },
  {
    name: '.fbOwFileWrite',
    type: 'FB_FileWrite',
    iGroup: 16448,
    iOffset: 6252,
    bitSize: 1312,
  },
  {
    name: '.fbOwDatenpuffer',
    type: 'FB_MemBufferMerge',
    comment: 'Datenpuffer zusammen setzten',
    iGroup: 16448,
    iOffset: 5652,
    bitSize: 288,
  },
  {
    name: '.fbOwGroesse',
    type: 'FB_FileTell',
    comment: 'Größe der Datei ermitteln',
    iGroup: 16448,
    iOffset: 6416,
    bitSize: 1152,
  },
  {
    name: '.fbOwLoeschen',
    type: 'FB_FileDelete',
    comment: 'Datei löschen',
    iGroup: 16448,
    iOffset: 6560,
    bitSize: 3200,
  },
  {
    name: '.EnergieZeileTemp',
    type: 'UDINT',
    comment: 'Zeile in der Datei',
    iGroup: 16448,
    iOffset: 9632,
    bitSize: 32,
  },
  {
    name: '.OwZeileTemp',
    type: 'UDINT',
    comment: 'Zeile in der Datei',
    iGroup: 16448,
    iOffset: 1728,
    bitSize: 32,
  },
  {
    name: '.EnergieTOC',
    type: 'ARRAY [1..100] OF ST_TOC',
    iGroup: 16448,
    iOffset: 9644,
    bitSize: 99200,
  },
  {
    name: '.OwTOC',
    type: 'ARRAY [1..100] OF ST_TOC',
    iGroup: 16448,
    iOffset: 22044,
    bitSize: 99200,
  },
  {
    name: '.EnergieTOCIndex',
    type: 'UDINT',
    comment: 'Index für Energie-TOC',
    iGroup: 16448,
    iOffset: 46844,
    bitSize: 32,
  },
  {
    name: '.OWTOCIndex',
    type: 'UDINT',
    comment: 'Index für OW-TOC',
    iGroup: 16448,
    iOffset: 1732,
    bitSize: 32,
  },
  {
    name: '.EnergieSpeicherplatz',
    type: 'REAL',
    comment: 'Wieviel Platz benötig die Energieaufzeichnung insgesamt??',
    iGroup: 16448,
    iOffset: 46856,
    bitSize: 32,
  },
  {
    name: '.EnergieSpeicherBerechnungIndex',
    type: 'UDINT',
    comment: 'Index für die Speicherplatz Berechnung',
    iGroup: 16448,
    iOffset: 46860,
    bitSize: 32,
  },
  {
    name: '.EnergieDateiLoeschen',
    type: 'BOOL',
    comment: 'ältester Eintrag der Energieaufzeichnung löschen',
    iGroup: 16448,
    iOffset: 5691,
    bitSize: 8,
  },
  {
    name: '.OwSpeicherplatz',
    type: 'REAL',
    comment: 'Wieviel Platz benötig die Energieaufzeichnung insgesamt??',
    iGroup: 16448,
    iOffset: 6960,
    bitSize: 32,
  },
  {
    name: '.OwSpeicherBerechnungIndex',
    type: 'UDINT',
    comment: 'Index für die Speicherplatz Berechnung',
    iGroup: 16448,
    iOffset: 6964,
    bitSize: 32,
  },
  {
    name: '.OwDateiLoeschen',
    type: 'BOOL',
    comment: 'ältester Eintrag der Energieaufzeichnung löschen',
    iGroup: 16448,
    iOffset: 1724,
    bitSize: 8,
  },
  {
    name: '.Skalierungsfaktor',
    type: 'REAL',
    comment:
      '*************************************************************************************** ****** Werte aus der Messklemme ************************************************ ****************************************************************************************',
    iGroup: 16448,
    iOffset: 933116,
    bitSize: 32,
  },
  {
    name: '.iAuxiliaryIndex',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 0,
    bitSize: 8,
  },
  {
    name: '.iAuxiliaryChannel',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 1,
    bitSize: 8,
  },
  {
    name: '.iAuxiliaryWert',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 4,
    bitSize: 32,
  },
  {
    name: '.SummeEnergie',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46880,
    bitSize: 32,
  },
  {
    name: '.Frequenz',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46884,
    bitSize: 32,
  },
  {
    name: '.SummeEnergieNegativ',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46888,
    bitSize: 32,
  },
  {
    name: '.SummeWirkleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46892,
    bitSize: 32,
  },
  {
    name: '.SummeBlindleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46896,
    bitSize: 32,
  },
  {
    name: '.SummeScheinleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46900,
    bitSize: 32,
  },
  {
    name: '.oAuxiliaryIndex',
    type: 'USINT',
    iGroup: 61488,
    iOffset: 0,
    bitSize: 8,
  },
  {
    name: '.oAuxiliaryChannel',
    type: 'USINT',
    comment: 'Phase 1',
    iGroup: 61488,
    iOffset: 1,
    bitSize: 8,
  },
  {
    name: '.iL1Status',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 8,
    bitSize: 8,
  },
  {
    name: '.iL1Strom',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 12,
    bitSize: 32,
  },
  {
    name: '.iL1Spannung',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 16,
    bitSize: 32,
  },
  {
    name: '.iL1Wirkleistung',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 20,
    bitSize: 32,
  },
  {
    name: '.iL1Index',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 24,
    bitSize: 8,
  },
  {
    name: '.iL1Wert',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 28,
    bitSize: 32,
  },
  {
    name: '.L1Strom',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46904,
    bitSize: 32,
  },
  {
    name: '.L1Spannung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46908,
    bitSize: 32,
  },
  {
    name: '.L1Wirkleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46912,
    bitSize: 32,
  },
  {
    name: '.L1Scheinleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46916,
    bitSize: 32,
  },
  {
    name: '.L1Blindleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46920,
    bitSize: 32,
  },
  {
    name: '.L1Energie',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46924,
    bitSize: 32,
  },
  {
    name: '.L1cosPHI',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46928,
    bitSize: 32,
  },
  {
    name: '.L1Frequenz',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46932,
    bitSize: 32,
  },
  {
    name: '.L1EnergieNegativ',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46936,
    bitSize: 32,
  },
  {
    name: '.L1WinkelLambda',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46940,
    bitSize: 32,
  },
  {
    name: '.oL1Index',
    type: 'USINT',
    comment: 'Phase 2',
    iGroup: 61488,
    iOffset: 2,
    bitSize: 8,
  },
  {
    name: '.iL2Status',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 32,
    bitSize: 8,
  },
  {
    name: '.iL2Strom',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 36,
    bitSize: 32,
  },
  {
    name: '.iL2Spannung',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 40,
    bitSize: 32,
  },
  {
    name: '.iL2Wirkleistung',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 44,
    bitSize: 32,
  },
  {
    name: '.iL2Index',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 48,
    bitSize: 8,
  },
  {
    name: '.iL2Wert',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 52,
    bitSize: 32,
  },
  {
    name: '.L2Strom',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46944,
    bitSize: 32,
  },
  {
    name: '.L2Spannung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46948,
    bitSize: 32,
  },
  {
    name: '.L2Wirkleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46952,
    bitSize: 32,
  },
  {
    name: '.L2Scheinleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46956,
    bitSize: 32,
  },
  {
    name: '.L2Blindleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46960,
    bitSize: 32,
  },
  {
    name: '.L2energie',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46964,
    bitSize: 32,
  },
  {
    name: '.L2cosPHI',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46968,
    bitSize: 32,
  },
  {
    name: '.L2Frequenz',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46972,
    bitSize: 32,
  },
  {
    name: '.L2EnergieNegativ',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46976,
    bitSize: 32,
  },
  {
    name: '.L2WinkelLambda',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46980,
    bitSize: 32,
  },
  {
    name: '.oL2Index',
    type: 'USINT',
    comment: 'Phase 3',
    iGroup: 61488,
    iOffset: 3,
    bitSize: 8,
  },
  {
    name: '.iL3Status',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 56,
    bitSize: 8,
  },
  {
    name: '.iL3Strom',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 60,
    bitSize: 32,
  },
  {
    name: '.iL3Spannung',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 64,
    bitSize: 32,
  },
  {
    name: '.iL3Wirkleistung',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 68,
    bitSize: 32,
  },
  {
    name: '.iL3Index',
    type: 'USINT',
    iGroup: 61472,
    iOffset: 72,
    bitSize: 8,
  },
  {
    name: '.iL3Wert',
    type: 'DINT',
    iGroup: 61472,
    iOffset: 76,
    bitSize: 32,
  },
  {
    name: '.L3Strom',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46984,
    bitSize: 32,
  },
  {
    name: '.L3Spannung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46988,
    bitSize: 32,
  },
  {
    name: '.L3Wirkleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46992,
    bitSize: 32,
  },
  {
    name: '.L3Scheinleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 46996,
    bitSize: 32,
  },
  {
    name: '.L3Blindleistung',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 47000,
    bitSize: 32,
  },
  {
    name: '.L3energie',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 47004,
    bitSize: 32,
  },
  {
    name: '.L3cosPHI',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 47008,
    bitSize: 32,
  },
  {
    name: '.L3Frequenz',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 47012,
    bitSize: 32,
  },
  {
    name: '.L3EnergieNegativ',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 47016,
    bitSize: 32,
  },
  {
    name: '.L3WinkelLambda',
    type: 'REAL',
    iGroup: 16448,
    iOffset: 47020,
    bitSize: 32,
  },
  {
    name: '.oL3Index',
    type: 'USINT',
    comment:
      '*************************************************************************************** ******Energieaufzeichnung triggern************************************************ ***************************************************************************************',
    iGroup: 61488,
    iOffset: 4,
    bitSize: 8,
  },
  {
    name: '.EnergieaufzeichnungTrigger',
    type: 'TON',
    comment: 'Einschaltverzögerung um jede Sekunden Messpunkte einzutragen',
    iGroup: 16448,
    iOffset: 47024,
    bitSize: 192,
  },
  {
    name: '.AllgemeinStep',
    type: 'USINT',
    comment: 'CASE-Variable um das Register auszulesen',
    iGroup: 16448,
    iOffset: 8319,
    bitSize: 8,
  },
  {
    name: '.L1Step',
    type: 'USINT',
    comment: 'CASE-Variable um das Register auszulesen',
    iGroup: 16448,
    iOffset: 47048,
    bitSize: 8,
  },
  {
    name: '.L2Step',
    type: 'USINT',
    comment: 'CASE-Variable um das Register auszulesen',
    iGroup: 16448,
    iOffset: 47049,
    bitSize: 8,
  },
  {
    name: '.L3Step',
    type: 'USINT',
    comment: 'CASE-Variable um das Register auszulesen',
    iGroup: 16448,
    iOffset: 47050,
    bitSize: 8,
  },
  {
    name: '.NetzanalyseStep',
    type: 'USINT',
    comment: 'VASe-Variable um die Netzanalyse auszulesen',
    iGroup: 16448,
    iOffset: 47051,
    bitSize: 8,
  },
  {
    name: '.Netzanalysespeicher',
    type: 'ARRAY [0..1] OF ST_Netzanalyse',
    comment: 'Speicher für die Netzanalyse',
    iGroup: 16448,
    iOffset: 6968,
    bitSize: 8832,
  },
  {
    name: '.NetzanalyseAktiv',
    type: 'BOOL',
    iGroup: 16448,
    iOffset: 1725,
    bitSize: 8,
  },
  {
    name: '.NetzanalysePhase',
    type: 'BYTE',
    comment: 'Welche Phase soll analysiert werden',
    iGroup: 16448,
    iOffset: 2023,
    bitSize: 8,
  },
  {
    name: '.NetzanalyseOberschwingung',
    type: 'BYTE',
    comment: 'Welche Oberwellenschwingung soll analysiert werden',
    iGroup: 16448,
    iOffset: 3057,
    bitSize: 8,
  },
  {
    name: '.Netzanalysespeichernr',
    type: 'DINT',
    comment: 'Netzanalyse speichern',
    iGroup: 16448,
    iOffset: 8072,
    bitSize: 32,
  },
  {
    name: '.Netzanalyselesen',
    type: 'DINT',
    comment: 'Netzanalyse lesen',
    iGroup: 16448,
    iOffset: 8076,
    bitSize: 32,
  },
  {
    name: '.Energiespeicher',
    type: 'ARRAY [0..1, 0..899] OF ST_Energiedatensatz',
    comment: 'Datenbank für die Energiemesswerte',
    iGroup: 16448,
    iOffset: 48160,
    bitSize: 2592000,
  },
  {
    name: '.index',
    type: 'DINT',
    comment: 'Index in der Datenbank',
    iGroup: 16448,
    iOffset: 444168,
    bitSize: 32,
  },
  {
    name: '.speichernr',
    type: 'DINT',
    comment: 'Datenbank',
    iGroup: 16448,
    iOffset: 444172,
    bitSize: 32,
  },
  {
    name: '.speicherlesen',
    type: 'DINT',
    iGroup: 16448,
    iOffset: 444176,
    bitSize: 32,
  },
  {
    name: '.ProfinetStatus',
    type: 'UINT',
    comment: 'Profinet Status',
    iGroup: 61472,
    iOffset: 800,
    bitSize: 16,
  },
  {
    name: '.iAutomatikEin',
    type: 'BOOL',
    comment: 'Autoamtik ein',
    iGroup: 61473,
    iOffset: 8000,
    bitSize: 1,
  },
  {
    name: '.iEinrichtbetriebAktiv',
    type: 'BOOL',
    comment: 'Einrichtbetrieb aktiv',
    iGroup: 61473,
    iOffset: 8001,
    bitSize: 1,
  },
  {
    name: '.iReglerfreigabeVerschub',
    type: 'BOOL',
    comment: 'Reglerfreigabe Verschub',
    iGroup: 61473,
    iOffset: 8002,
    bitSize: 1,
  },
  {
    name: '.iReglerfreigabeHub',
    type: 'BOOL',
    comment: 'Reglerfreigabe Hub',
    iGroup: 61473,
    iOffset: 8003,
    bitSize: 1,
  },
  {
    name: '.iReglerfreigabeDrehwerk',
    type: 'BOOL',
    comment: 'Reglerfreigabe Drehwerk',
    iGroup: 61473,
    iOffset: 8004,
    bitSize: 1,
  },
  {
    name: '.iReglerfreigabeKettenfoerderer1',
    type: 'BOOL',
    comment: 'Reglerfreigabe Kettenförderer 1',
    iGroup: 61473,
    iOffset: 8005,
    bitSize: 1,
  },
  {
    name: '.iReglerfreigabeKettenfoerderer2',
    type: 'BOOL',
    comment: 'Reglerfreigabe Kettenförderer 2',
    iGroup: 61473,
    iOffset: 8006,
    bitSize: 1,
  },
  {
    name: '.iReglerfreigabePumpe',
    type: 'BOOL',
    comment: 'Reglerfreigabe Pumpe',
    iGroup: 61473,
    iOffset: 8007,
    bitSize: 1,
  },
  {
    name: '.iESTEnergiesparmodus',
    type: 'BOOL',
    comment: 'EST Energiesparmodus',
    iGroup: 61473,
    iOffset: 8008,
    bitSize: 1,
  },
  {
    name: '.iVerpackungsanlageStandby',
    type: 'BOOL',
    comment: 'Verpackungsanlage Standby',
    iGroup: 61473,
    iOffset: 8009,
    bitSize: 1,
  },
  {
    name: '.iAuftragVollentleerung',
    type: 'BOOL',
    comment: 'Auftrag Vollentleerung',
    iGroup: 61473,
    iOffset: 8010,
    bitSize: 1,
  },
  {
    name: '.iAuftragTeilentleerung',
    type: 'BOOL',
    comment: 'Auftrag Teilentleerung',
    iGroup: 61473,
    iOffset: 8011,
    bitSize: 1,
  },
  {
    name: '.iAuftragimGreifer',
    type: 'BOOL',
    comment: 'Auftrag im Greifer',
    iGroup: 61473,
    iOffset: 8012,
    bitSize: 1,
  },
  {
    name: '.iESTSoerung',
    type: 'BOOL',
    comment: 'EST Störung',
    iGroup: 61473,
    iOffset: 8013,
    bitSize: 1,
  },
  {
    name: '.iESTMeldung',
    type: 'BOOL',
    comment: 'EST Meldung',
    iGroup: 61473,
    iOffset: 8014,
    bitSize: 1,
  },
  {
    name: '.iReserve10017',
    type: 'BOOL',
    comment: 'Reserve',
    iGroup: 61473,
    iOffset: 8015,
    bitSize: 1,
  },
  {
    name: '.iEnergiemessungAktivieren',
    type: 'BOOL',
    comment: 'Energiemessung aktivieren',
    iGroup: 61473,
    iOffset: 8016,
    bitSize: 1,
  },
  {
    name: '.iNetzanalyseAktivieren',
    type: 'BOOL',
    comment: 'Netzanalyse aktivieren',
    iGroup: 61473,
    iOffset: 8017,
    bitSize: 1,
  },
  {
    name: '.iReserve10022',
    type: 'BOOL',
    comment: 'Reseve',
    iGroup: 61473,
    iOffset: 8018,
    bitSize: 1,
  },
  {
    name: '.iWirkleistungESTberechnen',
    type: 'BOOL',
    comment: 'Wirkleistung der EST berechnen',
    iGroup: 61473,
    iOffset: 8019,
    bitSize: 1,
  },
  {
    name: '.iReserve10024',
    type: 'BOOL',
    comment: 'Reserve',
    iGroup: 61473,
    iOffset: 8020,
    bitSize: 1,
  },
  {
    name: '.iReserve10025',
    type: 'BOOL',
    comment: 'Reserve',
    iGroup: 61473,
    iOffset: 8021,
    bitSize: 1,
  },
  {
    name: '.iReserve10026',
    type: 'BOOL',
    comment: 'reserve',
    iGroup: 61473,
    iOffset: 8022,
    bitSize: 1,
  },
  {
    name: '.iReserve10027',
    type: 'BOOL',
    comment: 'Reserve',
    iGroup: 61473,
    iOffset: 8023,
    bitSize: 1,
  },
  {
    name: '.iIstpunktVerschub',
    type: 'DINT',
    comment: 'Ispunkt Verschub',
    iGroup: 61472,
    iOffset: 1012,
    bitSize: 32,
  },
  {
    name: '.iIstpunktHub',
    type: 'DINT',
    comment: 'Ispunkt Hub',
    iGroup: 61472,
    iOffset: 1016,
    bitSize: 32,
  },
  {
    name: '.iIstpunktDrehwerk',
    type: 'DINT',
    comment: 'Ispunkt Drehwerk',
    iGroup: 61472,
    iOffset: 1020,
    bitSize: 32,
  },
  {
    name: '.iDateAndTime',
    type: 'ARRAY [0..7] OF BYTE',
    comment: 'Date And Time',
    iGroup: 61472,
    iOffset: 1024,
    bitSize: 64,
  },
  {
    name: '.iKistengewicht',
    type: 'REAL',
    comment: 'Kistengewicht',
    iGroup: 61472,
    iOffset: 1036,
    bitSize: 32,
  },
  {
    name: '.iEntleergewicht',
    type: 'REAL',
    comment: 'Entleerstaion',
    iGroup: 61472,
    iOffset: 1040,
    bitSize: 32,
  },
  {
    name: '.iSkalierungsfaktor',
    type: 'REAL',
    comment: 'Skalierungsfaktor',
    iGroup: 61472,
    iOffset: 1044,
    bitSize: 32,
  },
  {
    name: '.oEnergie',
    type: 'REAL',
    comment: 'Energie',
    iGroup: 61488,
    iOffset: 1000,
    bitSize: 32,
  },
  {
    name: '.oScheinleistungGesamt',
    type: 'REAL',
    comment: 'Scheinleistung gesamt',
    iGroup: 61488,
    iOffset: 1004,
    bitSize: 32,
  },
  {
    name: '.oWirkleistungGesamt',
    type: 'REAL',
    comment: 'Wirkleistung gesamt',
    iGroup: 61488,
    iOffset: 1008,
    bitSize: 32,
  },
  {
    name: '.oBlindleistungGesamt',
    type: 'REAL',
    comment: 'Blindleistung gesamt',
    iGroup: 61488,
    iOffset: 1012,
    bitSize: 32,
  },
  {
    name: '.oL1Spannung',
    type: 'REAL',
    comment: 'L1: Spannmung',
    iGroup: 61488,
    iOffset: 1016,
    bitSize: 32,
  },
  {
    name: '.oL1Strom',
    type: 'REAL',
    comment: 'L1: Strom',
    iGroup: 61488,
    iOffset: 1020,
    bitSize: 32,
  },
  {
    name: '.oL2Spannung',
    type: 'REAL',
    comment: 'L2: Spannung',
    iGroup: 61488,
    iOffset: 1024,
    bitSize: 32,
  },
  {
    name: '.oL2Strom',
    type: 'REAL',
    comment: 'L1: Strom',
    iGroup: 61488,
    iOffset: 1028,
    bitSize: 32,
  },
  {
    name: '.oL3Spannung',
    type: 'REAL',
    comment: 'L3: Spannung',
    iGroup: 61488,
    iOffset: 1032,
    bitSize: 32,
  },
  {
    name: '.oL3Strom',
    type: 'REAL',
    comment: 'L3: Strom',
    iGroup: 61488,
    iOffset: 1036,
    bitSize: 32,
  },
  {
    name: '.MAX_AVERAGE_MEASURES',
    type: 'INT',
    comment: '2..100',
    iGroup: 16448,
    iOffset: 908206,
    bitSize: 16,
  },
  {
    name: '.GLOBAL_FORMAT_HASH_PREFIX_TYPE',
    type: 'E_HashPrefixTypes',
    comment: 'IEC prefixes for binary, octal or hexadecimal type',
    iGroup: 16448,
    iOffset: 908208,
    bitSize: 16,
  },
  {
    name: '.GLOBAL_SBCS_TABLE',
    type: 'E_SBCSType',
    comment: 'Windows SBCS (Single Byte Character Set) Code Page Table',
    iGroup: 16448,
    iOffset: 908210,
    bitSize: 16,
  },
  {
    name: '.GLOBAL_DCF77_PULSE_SPLIT',
    type: 'TIME',
    comment: '0 == pulse < 140ms, 1 == pulse > 140',
    iGroup: 16448,
    iOffset: 908212,
    bitSize: 32,
  },
  {
    name: '.GLOBAL_DCF77_SEQUENCE_CHECK',
    type: 'BOOL',
    comment: 'TRUE = Enable plausibility check (two telegrams are checked), FALSE = Disable check',
    iGroup: 16448,
    iOffset: 908205,
    bitSize: 8,
  },
  {
    name: '.DEFAULT_CSV_FIELD_SEP',
    type: 'BYTE',
    comment: 'semicolon (;) := 16#3B => german field separator, comma (,) := 16#2C => US field separator',
    iGroup: 16448,
    iOffset: 908216,
    bitSize: 8,
  },
  {
    name: '.EMPTY_ROUTE_ENTRY',
    type: 'ST_AmsRouteEntry',
    comment: 'System Service file functions',
    iGroup: 16448,
    iOffset: 915904,
    bitSize: 1184,
  },
  {
    name: '.EMPTY_ARG_VALUE',
    type: 'T_Arg',
    comment: 'Lower and upper case ASCII codes of hexadecimal digits',
    iGroup: 16448,
    iOffset: 916052,
    bitSize: 96,
  },
  {
    name: '.FORMAT_HEXASC_CODES',
    type: 'ARRAY [0..1, 0..15] OF BYTE',
    comment: 'ASCII to decimal and decimal digits to ASCII codes',
    iGroup: 16448,
    iOffset: 916064,
    bitSize: 256,
  },
  {
    name: '.FORMAT_DECASC_CODES',
    type: 'ARRAY [0..9] OF BYTE',
    comment: 'Default precision values ( -1 => disabled (prints all characters or has special function)',
    iGroup: 16448,
    iOffset: 916096,
    bitSize: 80,
  },
  {
    name: '.FORMAT_DEFAULT_PRECISION',
    type: 'ARRAY [0..11] OF INT',
    comment: 'plc var type support mask',
    iGroup: 16448,
    iOffset: 916106,
    bitSize: 192,
  },
  {
    name: '.FORMAT_TYPE_SUPPORT_MASK',
    type: 'ARRAY [0..11, 0..18] OF BOOL',
    comment: 'TYPEFIELD_EL',
    iGroup: 16448,
    iOffset: 916130,
    bitSize: 1824,
  },
  {
    name: '.FORMAT_PREFIX_SUPPORT_MASK',
    type: 'ARRAY [0..3, 0..11] OF BOOL',
    comment: 'PREFIXFLAG_HASH',
    iGroup: 16448,
    iOffset: 916358,
    bitSize: 384,
  },
  {
    name: '.FORMAT_HASH_PREFIX_STRING',
    type: 'ARRAY [0..1, 0..11] OF STRING(10)',
    comment: 'HASHPREFIX_STDC',
    iGroup: 16448,
    iOffset: 916406,
    bitSize: 2112,
  },
  {
    name: '.ARGTYPE_IS_SIGNED_TYPE',
    type: 'ARRAY [0..18] OF BOOL',
    iGroup: 16448,
    iOffset: 916670,
    bitSize: 152,
  },
  {
    name: '.ARGTYPE_IS_FLOAT_TYPE',
    type: 'ARRAY [0..18] OF BOOL',
    iGroup: 16448,
    iOffset: 916689,
    bitSize: 152,
  },
  {
    name: '.ARGTYPE_IS_STRING_TYPE',
    type: 'ARRAY [0..18] OF BOOL',
    iGroup: 16448,
    iOffset: 916708,
    bitSize: 152,
  },
  {
    name: '.ARGTYPE_IS_UNSIGNED_TYPE',
    type: 'ARRAY [0..18] OF BOOL',
    iGroup: 16448,
    iOffset: 916727,
    bitSize: 152,
  },
  {
    name: '.ARGTYPE_IS_BIT_TYPE',
    type: 'ARRAY [0..18] OF BOOL',
    iGroup: 16448,
    iOffset: 916746,
    bitSize: 152,
  },
  {
    name: '.SYSTEMTIME_MAX_MONTHDAYS',
    type: 'ARRAY [0..1, 1..12] OF WORD',
    iGroup: 16448,
    iOffset: 916766,
    bitSize: 384,
  },
  {
    name: '.SYSTEMTIME_MAX_YEARSDAY',
    type: 'ARRAY [0..1, 0..13] OF WORD',
    iGroup: 16448,
    iOffset: 916814,
    bitSize: 448,
  },
  {
    name: '.SYSTEMTIME_TICKSPERMSEC',
    type: 'T_ULARGE_INTEGER',
    comment: 'Number of 100ns ticks per millisecond',
    iGroup: 16448,
    iOffset: 916872,
    bitSize: 64,
  },
  {
    name: '.SYSTEMTIME_TICKSPERSEC',
    type: 'T_ULARGE_INTEGER',
    comment: 'Number of 100ns ticks per second',
    iGroup: 16448,
    iOffset: 916880,
    bitSize: 64,
  },
  {
    name: '.SYSTEMTIME_TICKSPERDAY',
    type: 'T_ULARGE_INTEGER',
    comment: 'Number of 100ns ticks per day',
    iGroup: 16448,
    iOffset: 916888,
    bitSize: 64,
  },
  {
    name: '.SYSTEMTIME_DATE_AND_TIME_MIN',
    type: 'T_ULARGE_INTEGER',
    comment: 'min. DT value as file time DT#1970-01-01-00:00:00',
    iGroup: 16448,
    iOffset: 916896,
    bitSize: 64,
  },
  {
    name: '.SYSTEMTIME_DATE_AND_TIME_MAX',
    type: 'T_ULARGE_INTEGER',
    comment: 'max. DT value as file time DT#2106-02-06-06:28:15',
    iGroup: 16448,
    iOffset: 916904,
    bitSize: 64,
  },
  {
    name: '.WEST_EUROPE_TZI',
    type: 'ST_TimeZoneInformation',
    comment: 'Windows SBCS tables',
    iGroup: 16448,
    iOffset: 916912,
    bitSize: 864,
  },
  {
    name: '.SBCS_TABLES',
    type: 'ARRAY [1..2] OF ST_SBCSTable',
    iGroup: 16448,
    iOffset: 917020,
    bitSize: 4096,
  },
  {
    name: '.ImQn_TABLE',
    type: 'ARRAY [0..31] OF LREAL',
    comment: 'CRC16-CCITT lookup table ( 0x1021 as generator polynomial )',
    iGroup: 16448,
    iOffset: 917532,
    bitSize: 2048,
  },
  {
    name: '.GLOBAL_CRC_CCITT_TABLE',
    type: 'ARRAY [0..255] OF WORD',
    iGroup: 16448,
    iOffset: 917788,
    bitSize: 4096,
  },
  {
    name: '.eGlobalSUpsState',
    type: 'E_S_UPS_State',
    comment: 'current ups state of S-UPS',
    iGroup: 16448,
    iOffset: 908218,
    bitSize: 16,
  },
];
