version: '3'

services:
  iobroker:
    build: ./iobroker
    container_name: iobroker-beckhoff-automation
    hostname: iobroker-beckhoff-automation
    # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
    expose:
      - 8081
    volumes:
      - ..:/workspace:cached
      - iobrokerdata-beckhoff-automation:/opt/iobroker
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - TZ=Europe/Berlin
      - SETGID=1000

  parcel:
    container_name: parcel-beckhoff-automation
    build: ./parcel
    expose:
      - 1234
    ports:
      - '1235:1235'
    volumes:
      - ..:/workspace:cached
    environment:
      - CHOKIDAR_USEPOLLING=1

  # Reverse proxy to load up-to-date admin sources from the repo
  nginx:
    image: nginx:latest
    depends_on:
      - iobroker
      - parcel
    links:
      - iobroker
      - parcel
    container_name: nginx-beckhoff-automation
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ..:/workspace:cached
    ports:
      # Make the ioBroker admin available under http://localhost:8082
      - 8082:80

volumes:
  iobrokerdata-beckhoff-automation:
